export const DISPLAY_SEARCH = 'DISPLAY_SEARCH';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const SWITCH_TAB = 'SWITCH_TAB';
export const UPDATE_INGREDIENT_OWNERSHIP = 'UPDATE_INGREDIENT_OWNERSHIP';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const FINISH_FETCHING_RECIPES = 'FINISH_FETCHING_RECIPES';
export const UPDATE_USER_INGREDIENTS_VIEW_LIST_DATA = 'UPDATE_USER_INGREDIENTS_VIEW_LIST_DATA';