export const DISPLAY_SEARCH = 'DISPLAY_SEARCH';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const SWITCH_TAB = 'SWITCH_TAB';
export const UPDATE_INGREDIENT_OWNERSHIP = 'UPDATE_INGREDIENT_OWNERSHIP';